### ISSUE TITLE
mol2xyz doesn't work

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/psikit#6]
```
>>> pk.read_from_smiles("c1ccccc1")
>>> pk.energy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kzfm/python/psikit/psikit/psikit.py", line 34, in energy
    self.geometry()
  File "/Users/kzfm/python/psikit/psikit/psikit.py", line 31, in geometry
    self.psi4.geometry(xyz)
  File "/Users/kzfm/anaconda3/lib/python3.6/site-packages/psi4/driver/molutil.py", line 305, in geometry
    molecule = core.Molecule.create_molecule_from_string(geom)
RuntimeError: 
Fatal Error: Illegal atom symbol in geometry specification:  on line

Error occurred in file: /Users/github/builds/conda-builds/psi4-multiout_1532543506730/work/psi4/src/psi4/libmints/molecule.cc on line: 1205
The most recent 5 function calls were:


```

**Comment by kzfm** [comment]
The spin multiplicity is wrong http://www.psicode.org/psi4manual/master/psithonmol.html

**Comment by iwatobipen** [comment]
I changed mol2xyz. The function calculates formal charge of molecule and embeds multiplicity. I checked benzene and worked.

**Comment by kzfm** [comment]
Now, it works well. Thx
